// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/ulid (interfaces: CustomULIDInterface)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_ulid.go -package=mock github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/ulid CustomULIDInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	ulid "github.com/oklog/ulid/v2"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomULIDInterface is a mock of CustomULIDInterface interface.
type MockCustomULIDInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomULIDInterfaceMockRecorder
	isgomock struct{}
}

// MockCustomULIDInterfaceMockRecorder is the mock recorder for MockCustomULIDInterface.
type MockCustomULIDInterfaceMockRecorder struct {
	mock *MockCustomULIDInterface
}

// NewMockCustomULIDInterface creates a new mock instance.
func NewMockCustomULIDInterface(ctrl *gomock.Controller) *MockCustomULIDInterface {
	mock := &MockCustomULIDInterface{ctrl: ctrl}
	mock.recorder = &MockCustomULIDInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomULIDInterface) EXPECT() *MockCustomULIDInterfaceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockCustomULIDInterface) New() (ulid.ULID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New")
	ret0, _ := ret[0].(ulid.ULID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockCustomULIDInterfaceMockRecorder) New() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockCustomULIDInterface)(nil).New))
}
