// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/validator (interfaces: CustomValidatorInterface)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_validator.go -package=mock github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/validator CustomValidatorInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	validator "github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/validator"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomValidatorInterface is a mock of CustomValidatorInterface interface.
type MockCustomValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomValidatorInterfaceMockRecorder
	isgomock struct{}
}

// MockCustomValidatorInterfaceMockRecorder is the mock recorder for MockCustomValidatorInterface.
type MockCustomValidatorInterfaceMockRecorder struct {
	mock *MockCustomValidatorInterface
}

// NewMockCustomValidatorInterface creates a new mock instance.
func NewMockCustomValidatorInterface(ctrl *gomock.Controller) *MockCustomValidatorInterface {
	mock := &MockCustomValidatorInterface{ctrl: ctrl}
	mock.recorder = &MockCustomValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomValidatorInterface) EXPECT() *MockCustomValidatorInterfaceMockRecorder {
	return m.recorder
}

// Validate mocks base method.
func (m *MockCustomValidatorInterface) Validate(data any) validator.ValidationErrors {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", data)
	ret0, _ := ret[0].(validator.ValidationErrors)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockCustomValidatorInterfaceMockRecorder) Validate(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockCustomValidatorInterface)(nil).Validate), data)
}
