// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/jwt (interfaces: CustomJwtInterface)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_jwt.go -package=mock github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/jwt CustomJwtInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	jwt "github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/jwt"
	gomock "go.uber.org/mock/gomock"
)

// MockCustomJwtInterface is a mock of CustomJwtInterface interface.
type MockCustomJwtInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomJwtInterfaceMockRecorder
	isgomock struct{}
}

// MockCustomJwtInterfaceMockRecorder is the mock recorder for MockCustomJwtInterface.
type MockCustomJwtInterfaceMockRecorder struct {
	mock *MockCustomJwtInterface
}

// NewMockCustomJwtInterface creates a new mock instance.
func NewMockCustomJwtInterface(ctrl *gomock.Controller) *MockCustomJwtInterface {
	mock := &MockCustomJwtInterface{ctrl: ctrl}
	mock.recorder = &MockCustomJwtInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomJwtInterface) EXPECT() *MockCustomJwtInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCustomJwtInterface) Create() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCustomJwtInterfaceMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCustomJwtInterface)(nil).Create))
}

// Decode mocks base method.
func (m *MockCustomJwtInterface) Decode(tokenString string, claims *jwt.Claims) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decode", tokenString, claims)
	ret0, _ := ret[0].(error)
	return ret0
}

// Decode indicates an expected call of Decode.
func (mr *MockCustomJwtInterfaceMockRecorder) Decode(tokenString, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decode", reflect.TypeOf((*MockCustomJwtInterface)(nil).Decode), tokenString, claims)
}
