// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/csv (interfaces: CustomCSVInterface)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_csv.go -package=mock github.com/ahargunyllib/hc-ppn-app/apps/bot-service/pkg/csv CustomCSVInterface
//

// Package mock is a generated GoMock package.
package mock

import (
	multipart "mime/multipart"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCustomCSVInterface is a mock of CustomCSVInterface interface.
type MockCustomCSVInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCustomCSVInterfaceMockRecorder
	isgomock struct{}
}

// MockCustomCSVInterfaceMockRecorder is the mock recorder for MockCustomCSVInterface.
type MockCustomCSVInterfaceMockRecorder struct {
	mock *MockCustomCSVInterface
}

// NewMockCustomCSVInterface creates a new mock instance.
func NewMockCustomCSVInterface(ctrl *gomock.Controller) *MockCustomCSVInterface {
	mock := &MockCustomCSVInterface{ctrl: ctrl}
	mock.recorder = &MockCustomCSVInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCustomCSVInterface) EXPECT() *MockCustomCSVInterfaceMockRecorder {
	return m.recorder
}

// ParseFileHeader mocks base method.
func (m *MockCustomCSVInterface) ParseFileHeader(fileHeader *multipart.FileHeader) ([][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseFileHeader", fileHeader)
	ret0, _ := ret[0].([][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseFileHeader indicates an expected call of ParseFileHeader.
func (mr *MockCustomCSVInterfaceMockRecorder) ParseFileHeader(fileHeader any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseFileHeader", reflect.TypeOf((*MockCustomCSVInterface)(nil).ParseFileHeader), fileHeader)
}
