// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ahargunyllib/hc-ppn-app/apps/bot-service/domain/contracts (interfaces: TopicRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../internal/app/topic/repository/mock/mock_topic_repository.go -package=mock github.com/ahargunyllib/hc-ppn-app/apps/bot-service/domain/contracts TopicRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	entity "github.com/ahargunyllib/hc-ppn-app/apps/bot-service/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTopicRepository is a mock of TopicRepository interface.
type MockTopicRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTopicRepositoryMockRecorder
	isgomock struct{}
}

// MockTopicRepositoryMockRecorder is the mock recorder for MockTopicRepository.
type MockTopicRepositoryMockRecorder struct {
	mock *MockTopicRepository
}

// NewMockTopicRepository creates a new mock instance.
func NewMockTopicRepository(ctrl *gomock.Controller) *MockTopicRepository {
	mock := &MockTopicRepository{ctrl: ctrl}
	mock.recorder = &MockTopicRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicRepository) EXPECT() *MockTopicRepositoryMockRecorder {
	return m.recorder
}

// BulkCreate mocks base method.
func (m *MockTopicRepository) BulkCreate(ctx context.Context, topics []entity.Topic) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkCreate", ctx, topics)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkCreate indicates an expected call of BulkCreate.
func (mr *MockTopicRepositoryMockRecorder) BulkCreate(ctx, topics any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkCreate", reflect.TypeOf((*MockTopicRepository)(nil).BulkCreate), ctx, topics)
}

// GetHotTopics mocks base method.
func (m *MockTopicRepository) GetHotTopics(ctx context.Context) ([]entity.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHotTopics", ctx)
	ret0, _ := ret[0].([]entity.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHotTopics indicates an expected call of GetHotTopics.
func (mr *MockTopicRepositoryMockRecorder) GetHotTopics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHotTopics", reflect.TypeOf((*MockTopicRepository)(nil).GetHotTopics), ctx)
}
